FROM python:3.9 AS base 

WORKDIR /src

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt 

FROM base as label_studio

CMD [ "label-studio" ] 

FROM base as streamlit 

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

# install chromedriver
RUN apt-get install -yqq unzip
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# docker email prompt bug 
RUN mkdir -p /root/.streamlit
RUN bash -c 'echo -e "\
[general]\n\
email = \"\"\n\
" > /root/.streamlit/credentials.toml'

# set display port to avoid crash
ENV DISPLAY=:99

COPY /streamlit/ .

CMD [ "streamlit","run","/src/main.py" ] 